#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $0 <file.tar.gz>"
	exit 1
fi

rm -rf /tmp.binupdate
gzip -dc "$1" > /tmp.binupdate || exit 1

/bin/rm -rf /bin /lib /usr /sbin
/tar xf /tmp.binupdate

rm -rf /tmp.binupdate
/bin/sync
