MAKEFLAGS += --no-builtin-rules --no-print-directory

CFLAGS += -O3 -Wall -Wstrict-prototypes -Wwrite-strings

CC = $(CROSS_COMPILE)gcc
AS = $(CROSS_COMPILE)as
AR = $(CROSS_COMPILE)ar
LD = $(CROSS_COMPILE)ld

V		= @
Q		= $(V:1=)
QUIET_CC	= $(Q:@=@echo   '       CC      '$(@:.d=.o);)
QUIET_LD	= $(Q:@=@echo   '       LD      '$@;)

OBJS = $(SRCS:.c=.o)
DEPS = $(SRCS:.c=.d)

PHONY += default all clean install
.PHONY: $(PHONY)
