$(DEPS): %.d : %.c
	$(QUIET_DEP)$(CC) $(CFLAGS) $(addprefix -I, $(INC)) $(addprefix -D, $(DEF)) -MM -o $*.d -c $<

$(OBJS): %.o : %.c
	$(QUIET_CC)$(CC) $(CFLAGS) $(addprefix -I, $(INC)) $(addprefix -D, $(DEF)) -c $< -o $@

clean:
	$(Q)$(RM) $(DEPS) $(OBJS) $(TARGETS) *~
