SWITCH_INC = $(TOP_DIR)/switch


ifeq ($(IMPL), lisa)
SWITCH_INC += $(TOP_DIR)/switch/lisa
endif

ifeq ($(IMPL), linux)
SWITCH_INC += $(TOP_DIR)/switch/linux
endif

ifeq ($(IMPL), openwrt)
SWITCH_INC += $(TOP_DIR)/switch/swconfig
endif
